### ISSUE TITLE
What does an MCC of 0.X mean?

### ISSUE THREAD

**Issue by joannacknight** [alan-turing-institute/ARC-MTQE#91]
For the report we want some analysis to show how to interpret the MCC values. e.g. look at precision, recall, confusion matrices for different MCC values. Want to understand how 'bad' the en-ja values are in particular.

**Comment by radka-j** [comment]
I don't think we need to do any further work on illustrating what MCC is since we already say in the text that you should really be looking at precision/recall performance.
